# .air.toml
root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
full_bin = "./tmp/main"
include_dir = ["routes", "models", "utils", "middlewares", "db"]
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "env"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
stop_on_error = true
send_interrupt = true
kill_delay = 500 # ms
rerun = true

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true